import {loadHeader} from './components/header/header.js';
import { loadFooter } from './components/footer/footer.js';
import { loadStart } from './components/start/start.js';
import { loadExtras } from './components/extras/extras.js';
import { loadRewards } from './components/rewards-banner/rewards.js';
import { loadPayments } from './components/payments/payments.js';
import { loadMenu } from './components/menu/menu.js';
import { loadQuestions } from './components/questions/questions.js';
import { loadSignUp } from './components/signup/signup.js';
import { loadSubheader } from './components/header/subheader.js';
import { loadStarBanner } from './components/starbanner/starbanner.js';
loadHeader();
loadSubheader();
loadStarBanner();
// loadBanner();
// loadStart();
// loadMenu();
// loadExtras();
// loadPayments();
// loadRewards();
// loadQuestions();
// loadFooter();

